<?php
namespace ResourceCatalog\Model;

interface IResourceCatalogTypeIdentify
{
    const TYPE_IDENTIFY = array(
        IResourceCatalog::TYPE['NULL'] => '',
        IResourceCatalog::TYPE['XBXZCF'] => 'XBXZCF',
        IResourceCatalog::TYPE['XBXZXK'] => 'XBXZXK',
        IResourceCatalog::TYPE['SXBZXRZRR'] => 'SXBZXRZRR',
        IResourceCatalog::TYPE['SXBZXRJG'] => 'SXBZXRJG',
        IResourceCatalog::TYPE['AJNSR'] => 'AJNSR',
        IResourceCatalog::TYPE['TQNMGGZ'] => 'TQNMGGZ',
        IResourceCatalog::TYPE['TQSB'] => 'TQSB',
        IResourceCatalog::TYPE['QNWSJGR'] => 'QNWSJGR',
        IResourceCatalog::TYPE['QNWSJZZ'] => 'QNWSJZZ',
        IResourceCatalog::TYPE['SCJRQY'] => 'SCJRQY',
        IResourceCatalog::TYPE['XZZLJ'] => 'XZZLJ',
        IResourceCatalog::TYPE['QGYXJS'] => 'QGYXJS',
        IResourceCatalog::TYPE['QGYXSXDY'] => 'QGYXSXDY',
        IResourceCatalog::TYPE['TEST'] => 'TEST',

        IResourceCatalog::TYPE['RYBZXX'] => 'RYBZXX',
        IResourceCatalog::TYPE['RYJLXX'] => 'RYJLXX',
        IResourceCatalog::TYPE['DFXYF'] => 'DFXYF',
        IResourceCatalog::TYPE['DFXBMDXXFR'] => 'DFXBMDXXFR',
        IResourceCatalog::TYPE['DFXRMDXXFR'] => 'DFXRMDXXFR',
        IResourceCatalog::TYPE['DFXBMDXXZRR'] => 'DFXBMDXXZRR',
        IResourceCatalog::TYPE['DFXRMDXXZRR'] => 'DFXRMDXXZRR',
        IResourceCatalog::TYPE['QIYEJBXXNEW'] => 'QIYEJBXXNEW',
        IResourceCatalog::TYPE['GTGSHXX'] => 'GTGSHXX',
        IResourceCatalog::TYPE['CMQYSBXX'] => 'CMQYSBXX',
        IResourceCatalog::TYPE['YPLSQYXX'] => 'YPLSQYXX',
        IResourceCatalog::TYPE['SXQYHMD'] => 'SXQYHMD',
        IResourceCatalog::TYPE['QYYCMLXX'] => 'QYYCMLXX',
        IResourceCatalog::TYPE['QYZXXX'] => 'QYZXXX',
        IResourceCatalog::TYPE['SFJDJGCYRYZGXX'] => 'SFJDJGCYRYZGXX',
        IResourceCatalog::TYPE['SFJDJGDJXX'] => 'SFJDJGDJXX',
        IResourceCatalog::TYPE['GZJGJBXX'] => 'GZJGJBXX',
        IResourceCatalog::TYPE['GZYXX'] => 'GZYXX',
        IResourceCatalog::TYPE['JCFLFWSXX'] => 'JCFLFWSXX',
        IResourceCatalog::TYPE['LSSWSXX'] => 'LSSWSXX',
        IResourceCatalog::TYPE['LSZYZGZXX'] => 'LSZYZGZXX',
        IResourceCatalog::TYPE['JSZGXX'] => 'JSZGXX',
        IResourceCatalog::TYPE['JYJGXINXI'] => 'JYJGXINXI',
        IResourceCatalog::TYPE['SJYXXS'] => 'SJYXXS',
        IResourceCatalog::TYPE['YLBXXX'] => 'YLBXXX',
        IResourceCatalog::TYPE['YZTQSBXXHMD'] => 'YZTQSBXXHMD',
        IResourceCatalog::TYPE['SBQYXX'] => 'SBQYXX',
        IResourceCatalog::TYPE['GZRYXX'] => 'GZRYXX',
        IResourceCatalog::TYPE['YZTQNMGGZHMD'] => 'YZTQNMGGZHMD',
        IResourceCatalog::TYPE['SLGCZBXX'] => 'SLGCZBXX',
        IResourceCatalog::TYPE['HSZYZGZXX'] => 'HSZYZGZXX',
        IResourceCatalog::TYPE['YSZYZCHBGZC'] => 'YSZYZCHBGZC',
        IResourceCatalog::TYPE['YSZYZGZXX'] => 'YSZYZGZXX',
        IResourceCatalog::TYPE['WSHJHSYWYHJCXX'] => 'WSHJHSYWYHJCXX',
        IResourceCatalog::TYPE['YLHJSFWJGXX'] => 'YLHJSFWJGXX',
        IResourceCatalog::TYPE['JBYFKZJGXX'] => 'JBYFKZJGXX',
        IResourceCatalog::TYPE['WSZYJSZGKSWJXX'] => 'WSZYJSZGKSWJXX',
        IResourceCatalog::TYPE['WXHXPQYBHGLQD'] => 'WXHXPQYBHGLQD',
        IResourceCatalog::TYPE['JXSZLJDW'] => 'JXSZLJDW',
        IResourceCatalog::TYPE['SLYSXKZXX'] => 'SLYSXKZXX',
        IResourceCatalog::TYPE['YXZZDWJBGXX'] => 'YXZZDWJBGXX',
        IResourceCatalog::TYPE['JDCWFXX'] => 'JDCWFXX',
        IResourceCatalog::TYPE['QSXXFR'] => 'QSXXFR',
        IResourceCatalog::TYPE['NSXXFR'] => 'NSXXFR',
        IResourceCatalog::TYPE['QYGSZXXX'] => 'QYGSZXXX',
        IResourceCatalog::TYPE['AJNSRXX'] => 'AJNSRXX',
        IResourceCatalog::TYPE['ZDSSWFAJXX'] => 'ZDSSWFAJXX',
        IResourceCatalog::TYPE['DBHXX'] => 'DBHXX',
        IResourceCatalog::TYPE['SHZZNJXX'] => 'SHZZNJXX',
        IResourceCatalog::TYPE['MBFQYML'] => 'MBFQYML',
        IResourceCatalog::TYPE['SHTTDJXX'] => 'SHTTDJXX',
        IResourceCatalog::TYPE['HRBXX'] => 'HRBXX',
        IResourceCatalog::TYPE['ZYZXX'] => 'ZYZXX',
        IResourceCatalog::TYPE['XSPJXX'] => 'XSPJXX',
        IResourceCatalog::TYPE['SXBZXJGXX'] => 'SXBZXJGXX',
        IResourceCatalog::TYPE['SXBZXRMD'] => 'SXBZXRMD',
        IResourceCatalog::TYPE['LSTDFWBA'] => 'LSTDFWBA',
        IResourceCatalog::TYPE['QYYH'] => 'QYYH',
        IResourceCatalog::TYPE['JCFLFWGZZJBXX'] => 'JCFLFWGZZJBXX',
        IResourceCatalog::TYPE['FRGYSYJFXX'] => 'FRGYSYJFXX',
        IResourceCatalog::TYPE['FRTQGYSYFXX'] => 'FRTQGYSYFXX',
        IResourceCatalog::TYPE['ZRRGYSYJFXX'] => 'ZRRGYSYJFXX',
        IResourceCatalog::TYPE['ZRRTQGYSYFXX'] => 'ZRRTQGYSYFXX',
        
        IResourceCatalog::TYPE['NSXXZRR'] => 'NSXXZRR',
        IResourceCatalog::TYPE['QSXXZRR'] => 'QSXXZRR',
        IResourceCatalog::TYPE['ZYJNZSXX'] => 'ZYJNZSXX',
        IResourceCatalog::TYPE['SYBXXX'] => 'SYBXXX',
        IResourceCatalog::TYPE['SHJZSXRYMD'] => 'SHJZSXRYMD',
    );
}
