<?php
namespace ResourceCatalog\Model;

interface IUserGroup extends IUserGroupIdentify
{
    const ID = array(
        'NULL' => 0,
        'XFGW' => 1,
        'XWXCBWMB' => 2,
        'XWZFW' => 3,
        'XFY' => 4,
        'XJCY' => 5,
        'XGAJ' => 6,
        'XWXZFXXZX' => 7,
        'XZFJRB' => 8,
        'XCZJ' => 9,
        'XGXJ' => 10,
        'XJYJ' => 11,
        'XSFJ' => 12,
        'XRSJ' => 13,
        'XZJJ' => 14,
        'ZGSL' => 15,
        'ZGBDST' => 16,
        'XSLJ' => 17,
        'XGDGS' => 18,
        'XLYJ' => 19,
        'XJTYSB' => 20,
        'XHBJ' => 21,
        'XSWJ' => 22,
        'XCGJ' => 23,
        'XMZJ' => 24,
        'XNYJ' => 25,
        'XWGXLJ' => 26,
        'XZRZYJ' => 27,
        'XWJW' => 28,
        'XSWJU' => 29,
        'XTJJ' => 30,
        'XSCJGJ' => 31,
        'XYJGLJ' => 32,
        'XZWFWGLB' => 33,
        'LXNSYH' => 34,
        'NHLXZH' => 35,
        'JHLXZH' => 36,
        'GHLXZH' => 37,
        'ZHLXZH' => 38,
        'YZYHLXZH' => 39,
        'XWSYDWBZBGS' => 40,
        'LXXSJJ' => 41,
        'LXXZGH' => 42,
        'LXXTW' => 43,
        'XQXJ' => 44,
        'XKJJ' => 45,
        'XRQGS' => 46,
        'XSWGS' => 47,
    );
}
